//store

{
	activityId:2,
	questions:[
		{question："我是题干",answer:['xxx','xxx1','xxx2','xxx3',1]},
		{question："我是题干",answer:['xxx','xxx1','xxx2','xxx3',1]}
	],
	ActivityDesc:{
		startTime:"2018-08-06",
		endTime:"2018-08-06",
		address:'百步亭花园路18号',
		describle:'活动说明',
		tel:'027-82782700',
	},
	history:[],
	myPrize:{},
	score:0,
	shareConfig:{
		img:'',//得绝对路径，
		title:''//标题,
		desc:''//描述,
		url:window.location.href,
	}
}
